spring:
  cache:
    type: none
  application:
    name: Managing a Movie Rental System

  datasource:
    url: jdbc:mysql://localhost:3306/movie_information_website
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  logging:
    level:
      org:
        springframework:
          transaction: DEBUG
          data:
            jpa:
              repository: DEBUG
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE

  server:
    port: 8080
    servlet:
      context-path: /aladdin
    tomcat:
      uri-encoding: UTF-8

  web:
    locale: tr-TR

email:
  toEmail: ${TO_EMAIL}
  fromEmail: ${FROM_EMAIL}


API:
  key: ${OMDB}
